title: "Workshop on Trustworthy AI"
url: https://trust-ai-workshop.github.io/
navigation:
   - title: Schedule
     url: /schedule.html
   - title: Participants
     url: /participants.html
theme: jekyll-theme-cayman
