title: "Workshop on Trustworthy AI"
url: https://trust-ai-workshop.github.io/
navigation:
   - title: Schedule
     url: /schedule.html
   - title: Register
     url: /register.html
   - title: Participants
     url: /participants.html
   - title: Local Arrangements
     url: /local.html
theme: jekyll-theme-cayman
